name: Update Package Version

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:      # 允许手动触发

env:
  REPO_NAME: "daeuniverse/dae"

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest commit hash and date
      id: version
      run: |
        commit_hash=$(curl -s "https://api.github.com/repos/${REPO_NAME}/commits/main" | grep -oP '(?<="sha": ")[^"]*' | head -1)
        today=$(date +%Y.%m.%d)
        echo "commit_hash=${commit_hash}" >> $GITHUB_OUTPUT
        echo "today=${today}" >> $GITHUB_OUTPUT

    - name: Update Makefile
      id: update
      run: |
        # 保存当前commit hash用于比较
        old_hash=$(grep "PKG_SOURCE_VERSION:=" Makefile | cut -d'=' -f2)
        # 更新版本号和commit hash
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${today}/" duck/Makefile
        sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${commit_hash}/" duck/Makefile
        
        new_hash=$(grep "PKG_SOURCE_VERSION:=" Makefile | cut -d'=' -f2)
        if [ "$old_hash" != "$new_hash" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
      env:
        today: ${{ steps.version.outputs.today }}
        commit_hash: ${{ steps.version.outputs.commit_hash }}

    - name: Commit changes
      if: steps.update.outputs.has_changes == 'true'
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add Makefile
        git commit -m "duck: Update to ${today} (${commit_hash:0:7})"
        git push
      env:
        today: ${{ steps.version.outputs.today }}
        commit_hash: ${{ steps.version.outputs.commit_hash }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2